apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-n8n
  labels:
    app: n8n
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
      - name: n8n
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.env.N8N_PORT }}
        env:
        - name: N8N_HOST
          value: {{ .Values.env.N8N_HOST }}
        - name: N8N_PORT
          value: "{{ .Values.env.N8N_PORT }}"
        - name: DB_TYPE
          value: {{ .Values.env.DB_TYPE }}
        - name: DB_SQLITE_FILE
          value: {{ .Values.env.DB_SQLITE_FILE }}
        - name: N8N_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.encryptionKey.name }}
              key: {{ .Values.secrets.encryptionKey.key }}
        volumeMounts:
        - name: data
          mountPath: {{ .Values.persistence.mountPath }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.env.N8N_PORT }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-n8n-data