apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-n8n-data
  namespace: {{ .Values.namespace.name | default "n8n" }}
  labels:
    app: n8n
    managed-by: helm
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  storageClassName: {{ .Values.persistence.storageClass | default "local-path" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "5Gi" }}