apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-n8n-secrets
  namespace: {{ .Values.namespace.name | default "n8n" }}
  labels:
    app: n8n
type: Opaque
stringData:
  # N8N加密密钥
  N8N_ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey.value | default (randAlphaNum 32) }}
  
  # 可选的数据库凭据（如果使用外部数据库）
  DB_USERNAME: {{ .Values.secrets.database.username | default "" }}
  DB_PASSWORD: {{ .Values.secrets.database.password | default "" }}