apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
      - name: wordpress
        image: {{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}
        imagePullPolicy: {{ .Values.wordpress.image.pullPolicy }}
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Release.Name }}-mysql
        - name: WORDPRESS_DB_USER
          value: {{ .Values.mysql.user }}
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.mysql.userPassword.name }}
              key: {{ .Values.secrets.mysql.userPassword.key }}
        - name: WORDPRESS_DB_NAME
          value: {{ .Values.mysql.database }}
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: {{ .Values.resources.wordpress.limits.cpu }}
            memory: {{ .Values.resources.wordpress.limits.memory }}
          requests:
            cpu: {{ .Values.resources.wordpress.requests.cpu }}
            memory: {{ .Values.resources.wordpress.requests.memory }}
        volumeMounts:
        - name: wordpress-data
          mountPath: /var/www/html
      volumes:
      - name: wordpress-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-wordpress-pvc
